import { StringModule } from "@faker-js/faker";

export const selector = {
  // sapDisputeCaseCreatePage selectors
  createButton: `//bdi[contains(@id,"DisputeCase--ActionCreateWithoutInvoice")]`,
  customerIdInput: `(//div[@class='sapMInputBaseContentWrapper']/input)[1]`,
  createConfirmButton:`//bdi[contains(@id,'btnCreateWithoutInvoiceConfirmDialog')]`,
  caseTitleInput: `(//bdi[text()='Case Title']/following::input)[1]`,
  categoryInput: `//bdi[text()='Category']/following::input[1]`,
  priorityInput: `(//bdi[text()='Priority']/following::input[1])[2]`,
  reasonInput: `//bdi[text()='Reason']/following::input[1]`,
  rootCauseInput: `//bdi[text()='Root Cause Code']/following::input[1]`,
  caseCreateButton: `//bdi[contains(@id,"DisputeCase--activate")]`,
  

  managePaymentBlocks:`//a[contains(@aria-label,"Manage Payment Blocks")]`,  // sapDisputeCasePage selectors
  manageDisputeCases: `//a[contains(@aria-label,"Manage Dispute Cases")]`,
  
  customerKeyInput:
    `//label[@title="Key of Customer in Accounts Receivable Accounting"]/following-sibling::div//input`,
  companyCodeInput:
    `//label[@title="Company Code"]/following-sibling::div//input`,
  // goButton removed duplicate
  navigationIcon: `//span[@aria-label="Navigation"]`,
  editButton: `//bdi[contains(@id,'DisputeCase--edit')]`,
  caseStatusDropdown: `//span[contains(@aria-labelledby,"CaseStatus")]`,
  closedStatus: `//span[contains(text(),"Closed")]`,
  saveButton: `//bdi[text()="Save"]`,
  busyIndicator: `//div[contains(@class,"sapUiLocalBusyIndicatorAnimation")]`,
  navigationMenu: `//span[@aria-label="Navigation menu"]`,
  manageDisputeCasesTitle: `//span[contains(@id,'titleText') and text()='Manage Dispute Cases']`,
  allDisputeCases: `//div[contains(text(),'All Dispute Cases')]`,
  closedDisputeCases:`//div[contains(text(),'Closed Dispute Cases')]`,
  openDisputeCases: `//div[contains(text(),'Open Dispute Cases')]`,
  disputeCaseRow: `//tbody[contains(@class,"sapMTableTBody ")]//tr/td[contains(@id,'DisputeCase')]`,
  disputeAfterClose:`//tbody[contains(@class,"sapMTableTBody ")]//tr/td[contains(@id,'DisputeCase--responsiveTable-nodata-text')]`,
  caseIdInput: `//label[@title="Case ID"]/following-sibling::div//input`,
  supplierInput:`//label[@title="Account Number of Supplier"]/following-sibling::div//input`,
  supplierFirstRow:`//table[contains(@id,"filterItemControl_BASIC-Supplier-popup-table")]//tr[2]/td[2]`,
  disputeRow:(CASE_ID:string)=>`(//tbody//tr[.//td[contains(.,"${CASE_ID}")]])[1]`,
  // Manage Customer Line Items selectors
  manageCustomerLineItems: `//a[contains(@aria-label,"Manage Customer Line Items")]`,
  customerValueHelp: `(//span[@aria-label="Show Value Help"])[1]`,
  customerRadio: '(//div[@class="sapUiTableCell sapUiTableContentCell sapUiTableRowSelectionCell"])[1]',
  // Aliases used by manage-customer-line-items step definitions
  customerLineItemsStatus: `//span[@class='sapMSltLabel']`,
  customerLineStatus_open: `//li[text()='Open Items']`,
  openKeyDatePicker: `//span[contains(@id,'BASIC-KeyDate-input-vhi')]`,
  selectDayAstdy: `(//span[text()='Today'])[1]`,
  // okButton removed duplicate
  companyValueHelp: `(//span[@aria-label="Show Value Help"])[2]`,
  companyRadio: '(//div[@class="sapUiTableCell sapUiTableContentCell sapUiTableRowSelectionCell"])[1]',
  goButton: `//bdi[text()='Go']`,
  customerNumber: `(//tr[contains(@id,"application-Customer-manageLineItems") and contains(@id,"TableItems-rows-row0")]//a/span)[1]`,
  firstRowCheckbox: `(//div[contains(@id,"rowsel")])[1]`,
  editLineItemsButton: `//bdi[contains(@id,"display.ChangeButton-BDI-content")]`,
  //span[contains(@id,"SelectChangeDocumentsPaymentBlock-label") and @class="sapMSelectListItemText"]
  itemPaymentBlockDropdown: `//span[contains(@id,"SelectChangeDocumentsPaymentBlock-arrow")]`,
  manualPaymentBlockedOption: `//li[text()="B (Manual paym blocked)"]`,
  settingsIcon: `//span[contains(@id,"btnPersonalisation-img")]`,
  settingsSearchInput: `//input[@aria-label="Search"]`,
  settingsCheckbox: `(//div[contains(@class,"sapMCbBg sapMCbHoverable sapMCbActiveStateOff sapMCbMark")])[2]`,
  settingsConfirmButton: `//bdi[contains(@id,"confirmBtn-BDI-content")]`,
  itemPaymentBlockValue: `((//tr[contains(@id,"TableItems-rows-row")])[1]//td[contains(@class,"sapUiTableCellLast")]//div//span)`,
  // sapLoginPage selectors
  usernameInput: `//input[@placeholder="Email, User ID or Login Name"]`,
  nextButton: `//div[@class="fn-button__text"]`,
  passwordInput: `//input[@id='j_password']`,
  signInButton: `//div[text()='Continue']`,
  Finance: `//div[contains(@id,'header')]/span[text()='Finance']`,

  // SAPPostPayPage selectors
  postpay_url: `https://my426318.s4hana.cloud.sap/ui#Customer-postPayment`,
  docDateInput: `//input[contains(@id,'post.docDateInput-datePicker-inner')]`,
  fiscalPeriodInput: `//input[contains(@id,"post.fiscalPeriod-input-inner")]`,
  glAccountInput: `//input[contains(@id,"post.gLAccount-input-inner")]`,
  pettyCashOption: `(//bdi[text()="Petty Cash"])[1]`,
  amountCurrencyIcon: `//span[contains(@id,'post.amountInTransCrcyInput-sfEdit-input-vhi')]`,
  currencySearchInput: `(//input[@aria-label="Search"])[1]`,
  currencySearchButton: `//div[contains(@id,"post.amountInTransCrcyInput-sfEdit-input-valueHelpDialog-smartFilterBar-btnBasicSearch-search")]`,
  currencySelect: `//span[text()="Indian Rupee"]`,
  amountInput: ` //input[contains(@id,"post.amountInTransCrcyInput-input-inner")]`,
  postButton: `//bdi[text()="Post"]`,
  errorMsg: `//div[@class="sapMSLITitleOnly"]`,
  okButton: `//bdi[text()="OK"]`,
  accountTypeDropdown: `//bdi[text()="Account Type/Account ID"]//following::span[text()="Customer"]`,
  customerTypeOption: `//li[contains(@id,"post.AccountType.Customer")]`,
  customerAccountIcon: `//span[contains(@id,'post.customerAccountInput-input-vhi')]`,
  selectCustomerText: `text=Select: Customer`,
  customerOption: `text=SILVERSTAR`,
  proposeItemsButton: `(//bdi[text()="Propose Items"])[1]`,
  amountText: `(//span[contains(@id,'amountText')])`,
  amountRowButton: (elementText: string) => `//tr[.//span[text()='${elementText}']]//button`,
  successMsg: `//span[contains(text(),"Success")]`,
  // Additional selectors for editing dispute case
  caseReasonDropdown: `//span[contains(@aria-labelledby,'CaseReason')]`,
  caseReasonOption:(elementText:string)=>`//div[contains(@data-sap-ui,"CaseReason::Field-comboBoxEdit-popup")]//span[text()='${elementText}']`,
  caseCategoryDropdown: `//span[contains(@aria-labelledby,'CaseCategory')]`,
  caseCategoryOption:(elementText:string)=>`//div[contains(@data-sap-ui,"CaseCategory::Field-comboBoxEdit-popup")]//span[text()='${elementText}']`,
  disputeRootCauseDropdown: `//span[contains(@aria-labelledby,'DisputeCaseRootCause')]`,
  rootCauseOption:(elementText:string)=>`//div[contains(@data-sap-ui,"DisputeCaseRootCause::Field-comboBoxEdit-popup")]//span[text()='${elementText}']`,
    // generic option matcher by visible text (use with exact text)
  customerLinkSpan: `//a[contains(@data-sap-ui,"Customer")]/span`,
  toastSelector: `//span[@class='sapMMessageToastHiddenFocusable']/..`,
  GoButtoninManageCustomer:`//button[contains(@id,"SmartFilterBar-btnGo")]`,
  ClickSupplierStatus:`//span[contains(@aria-labelledby,"BASIC-Status-arrow-label")]`,
  SelectBlockedStatus:`//span[text()='Account Blocked']`,
  GoButtoninPaymentBlocks:`//button[contains(@id,"btnGo")]`,
  BlockedSupplier:(supplierId:string)=>`(//tbody//tr[.//td[contains(.,"${supplierId} ")]])[1]`,
  UnblockSupplierButton:`//button[.//bdi[text()='Unblock Supplier']]`,
  ToastMsg:`//div[contains(@class,"sapMMessageToast ")]`,
  ReopenCaseButton:`//button[.//bdi[text()='Reopen Dispute Case']]`,
  ReopenDropdown:`//span[contains(@id,"DisputeCaseReopenStatus-comboBoxEdit") and @role="button"]`,
  ReopenedOption:`//span[contains(text(),'Re-Opened')]`,
  ConfirmReopeningOfCase:`//footer[@class='sapMDialogFooter']//bdi[text()='Reopen Dispute Case']`,
  CaseIdDetails:`//h2[contains(@id,"ObjectPageDynamicHeaderTitle")]/span`,
  
//BlockSupplierLineItemforPayment selectors
manageSupplierLineItems: `//a[contains(@aria-label,"Manage Supplier Line Items")]`,
enterSupplierValue:`//input[contains(@id,'Supplier-inner')]`,
//clickOnCustomer:`//tr[contains(@id,'BASIC-Supplier-0')]`,
enterCompanyCode:`//input[contains(@id,'CompanyCode-inner')]`,
//clickonCompanyCode:`//tr[contains(@id,'BASIC-CompanyCode-0')]`,
selectStauts:`//span[@class='sapMSltLabel']`,
SelectOpenItems:`//li[text()='Open Items']`,
keyDate:`//span[contains(@id,'BASIC-KeyDate-input-vhi')]`,
clickDate:`(//span[text()='Today'])[1]`,
ItemType:`(//span[contains(@id,'CustomMultiComboBoxDueItemCategory')])[1]`,
//clickNormalItem:`(//span[text()='Normal Items'])[1]`,
clickGo:`//bdi[text()='Go']`,
clickonCheckbox:`//div[contains(@id,'TableItems-rowsel0')]`,
clickOnBlockPayment:`//span[contains(@id,'ButtonBlockPayment-inner')]`,
blockResaon:`(//span[contains(@id,'SelectItemBlockReason')])[1]`,
selectBlockReason:`//li[text()='A (Blocked for payment)']`,
blockNotes:`(//div[@class='sapMInputBaseContentWrapper'])[1]`,
enterText:`//textarea[contains(@id,'TextAreaItemBlockingNote-inner')]`,
clikcOnOk:`//bdi[text()='OK']`,
clickOnMCLI:`(//span[text()='Manage Supplier Line Items'])[1]`,
clickOnFinance:`(//span[text()='Finance'])[1]`,
clickManagePayment:`//a[contains(@aria-label,"Manage Payment Blocks")]`,
clickOnUnblock:`//span[text()='Unblocked']`,
clickOnMore:`(//span[text()='More'])[5]`,
blockItem:`//span[text()='Item Blocked']`,
status:`(//span[contains(@id,'Status-text')])[4]`,


searchButton:`//a[@aria-label="Open Search"]`,
serchInput:`//input[@id="searchFieldInShell-input-inner"]`,
manageCustomerContactInSearch:`//b[text()='Manage Customer Contacts']`,
businessPartnerInput:`//label[@title="Business Partner Number"]/following-sibling::div//input`,
collectionSegmentInput:`//label[@title="Collection Segment"]/following-sibling::div//input`,
finishedCustomerContact:`//div[contains(text(),"Finished Customer Contacts")]`,
firstContactRow:`//table[contains(@id,"CustomerContactAttribute--responsiveTable")]/tbody/tr[1]`,
editInContactPage:`//button[contains(@id,"CustomerContactAttribute--edit")]`,
contactTypeInput:` //input[contains(@aria-labelledby,"CustomerContactType") and contains(@id,'ObjectPage.view.Details')]`,
visitContactType:`//span[contains(text(),"Visit")]`,
opendatepicker:`//span[@aria-label="Open Picker"]`,
selectDate:`//div[@data-sap-day="20250914"]`,
selectHour:`//div[@aria-label="Hours"]`,
selectMinutes:`//div[@aria-label="Minutes"]`,
selectPm:` //div[text()="PM"]`,
clickOk:`//bdi[text()="OK"]`,
clickSave:`//bdi[text()="Save"]`,

//Customer Contact for Business Partner
clickOnProcessReceivables:`//a[contains(@aria-label,'Process Receivables')]`,
clickOnIcon:`//span[contains(@id,'BASIC-BusinessPartner-vhi')]`,
enterOnSearch:`(//input[@aria-label='Search'])[1]`,
clickOnGO:`(//bdi[text()='Go'])[1]`,
clickOnbpChechbox:`//div[contains(@id,'rowsel0')]`,
clickOnOk:`//span[contains(@id,'ok-content')]`,
clickOnSegmentIcon:`(//span[contains(@id,'BASIC-CollectionSegment-arrow')])[1]`,
enterSegement:`//span[text()='YT_SEGMT01 (Collection Segment YT_SEGMT01)']`,
enterSegementCompanyCode:`//input[contains(@id,'CompanyCode-inner')]`,
clickOnItem:`(//div[@class='sapMObjectIdentifier'])[1]`,
clickOnCreateContact:`//bdi[contains(text(),'Customer Contact')]`,
clickOnResultContact:`(//span[contains(@id,'CustomerContactResult::Field-comboBoxEdit-arrow')])[1]`,
clickOnResult:`//span[text()='002 (Customer Not Reached)']`,
enterContantPerson:`//input[contains(@id,'ContactPersonName')]`,
clickOnCreateButton:`(//bdi[text()='Create'])[4]`,


};
